pipeline:

  build:
    image: quay.io/ukhomeofficedigital/scala-sbt:v0.3.1
    commands:
    - /root/entrypoint.sh
    - sbt test publish docker:stage
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: ARTIFACTORY_PASSWORD
    ARTIFACTORY_USERNAME: drt-artifactory-ci
    when:
      event:
      - push


  build_push_to_ecr:
    image: quay.io/ukhomeofficedigital/ecr:latest
    secrets:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    repo: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/drt/drt-cirium
    build_args:
    - APP_BUILD=${DRONE_COMMIT_SHA}
    tags:
    - latest
    - ${DRONE_COMMIT_SHA}
    - ${DRONE_BUILD_NUMBER}
    when:
      event:
        - push


