---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: analysis
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.0.0
  commands:
    - /root/entrypoint.sh
    - sbt -ivy ./.ivy2 dependencyCheck
    - sbt scalastyle | true
    - sbt scapegoat | true
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: ARTIFACTORY_PASSWORD
    ARTIFACTORY_USERNAME: scala-test-token
    ENV_LOG_LEVEL: ERROR
  when:
    event:
      - push

- name: build
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/scala-sbt:latest
  commands:
    - /root/entrypoint.sh
    - sbt test +publish docker:stage
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: ARTIFACTORY_PASSWORD
    ARTIFACTORY_USERNAME: scala-test-token
  when:
    event:
    - push

- name: publish
  image: plugins/ecr
  environment:
    AWS_REGION: eu-west-2
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    repo: drt/drt-cirium
    registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
    tags:
      - B${DRONE_BUILD_NUMBER}
      - latest
  when:
    event:
      - push

...


