---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:

- name: build
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/scala-sbt:latest
  commands:
    - /root/entrypoint.sh
    - sbt docker:stage
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: ARTIFACTORY_TOKEN
    ARTIFACTORY_USERNAME: ben.eppel@digital.homeoffice.gov.uk
  when:
    event:
    - push

- name: publish
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/ecr:latest
  settings:
    build_args:
    - APP_BUILD=${DRONE_COMMIT_SHA}
    repo: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/drt/drt-cirium
    tags:
    - latest
    - ${DRONE_COMMIT_SHA}
    - ${DRONE_BUILD_NUMBER}
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  when:
    event:
    - push


...
